import type { Team } from "../types/worldCup";

const flagImageByTeamId: Record<string, string> = {
  argentina: "https://flagcdn.com/w80/ar.png",
  france: "https://flagcdn.com/w80/fr.png",
  brazil: "https://flagcdn.com/w80/br.png",
  england: "https://flagcdn.com/w80/gb-eng.png",
  spain: "https://flagcdn.com/w80/es.png",
  portugal: "https://flagcdn.com/w80/pt.png",
  germany: "https://flagcdn.com/w80/de.png",
  netherlands: "https://flagcdn.com/w80/nl.png",
  usa: "https://flagcdn.com/w80/us.png",
  mexico: "https://flagcdn.com/w80/mx.png",
  japan: "https://flagcdn.com/w80/jp.png",
  morocco: "https://flagcdn.com/w80/ma.png",
  "south-africa": "https://flagcdn.com/w80/za.png",
  "south-korea": "https://flagcdn.com/w80/kr.png",
  czechia: "https://flagcdn.com/w80/cz.png",
  canada: "https://flagcdn.com/w80/ca.png",
  "bosnia-herzegovina": "https://flagcdn.com/w80/ba.png",
  qatar: "https://flagcdn.com/w80/qa.png",
  switzerland: "https://flagcdn.com/w80/ch.png",
  haiti: "https://flagcdn.com/w80/ht.png",
  scotland: "https://flagcdn.com/w80/gb-sct.png",
  turkiye: "https://flagcdn.com/w80/tr.png",
  australia: "https://flagcdn.com/w80/au.png",
  paraguay: "https://flagcdn.com/w80/py.png",
  curacao: "https://flagcdn.com/w80/cw.png",
  "cote-divoire": "https://flagcdn.com/w80/ci.png",
  ecuador: "https://flagcdn.com/w80/ec.png",
  sweden: "https://flagcdn.com/w80/se.png",
  tunisia: "https://flagcdn.com/w80/tn.png",
  belgium: "https://flagcdn.com/w80/be.png",
  iran: "https://flagcdn.com/w80/ir.png",
  egypt: "https://flagcdn.com/w80/eg.png",
  "new-zealand": "https://flagcdn.com/w80/nz.png",
  "cape-verde": "https://flagcdn.com/w80/cv.png",
  "saudi-arabia": "https://flagcdn.com/w80/sa.png",
  uruguay: "https://flagcdn.com/w80/uy.png",
  senegal: "https://flagcdn.com/w80/sn.png",
  norway: "https://flagcdn.com/w80/no.png",
  iraq: "https://flagcdn.com/w80/iq.png",
  algeria: "https://flagcdn.com/w80/dz.png",
  austria: "https://flagcdn.com/w80/at.png",
  jordan: "https://flagcdn.com/w80/jo.png",
  colombia: "https://flagcdn.com/w80/co.png",
  uzbekistan: "https://flagcdn.com/w80/uz.png",
  "dr-congo": "https://flagcdn.com/w80/cd.png",
  croatia: "https://flagcdn.com/w80/hr.png",
  ghana: "https://flagcdn.com/w80/gh.png",
  panama: "https://flagcdn.com/w80/pa.png",
};

export const getFlagImageUrl = (team?: Team) => (team ? team.flagImageUrl ?? flagImageByTeamId[team.id] : undefined);
